project:
  type: website
  resources:
   - assets/*

website:
  title: "embedio"
  reader-mode: true
  repo-url: https://github.com/coatless-quarto/embedio/
  repo-actions: [edit, issue]
  sidebar:
    style: "floating"
    search: true
    tools:
      - icon: github
        href: https://github.com/coatless-quarto/embedio/
    contents: 
      - text: "Home"
        file: index.qmd
      - section: "Demos"
        contents:
        - text: "PDF"
          href: qembedio-embed-pdf.qmd
        - text: "RevealJS"
          href: qembedio-embed-revealjs.qmd
        - text: "Audio"
          href: qembedio-embed-audio.qmd
        # - text: "HTML"
        # - text: "Maps"
        # - text: "Social"
      - section: "Support"
        contents:
        - text: "FAQ"
          href: qembedio-faq.qmd
        - text: "Submit an issue"
          href: https://github.com/coatless-quarto/embedio/issues/new/choose
      - section: "Extra"
        contents:
        - qembedio-release-notes.qmd

format: 
  html:
    toc: true
