---
title: "Home"
format: 
  html:
    toc: false
---

The `embedio` shortcode extension allows you to incorporate different file types into Quarto HTML documents by using Quarto's shortcode mechanism.

## Installation

To install the `embedio` shortcode extension, follow these steps:

1. Open your terminal.

2. Execute the following command:

```bash
quarto add coatless-quarto/embedio
```

This command will download and install the shortcode extension under the `_extensions` subdirectory of your Quarto project. If you are using version control, ensure that you include this directory in your repository.

## Usage

We presently support the following shortcodes:

| Shortcode  | Description                                                     |
|------------|-----------------------------------------------------------------|
| [`audio`](qembedio-embed-audio.qmd)    | Embeds an audio player with optional caption and download link. |
| [`pdf`](qembedio-embed-pdf.qmd)      | Embeds a PDF file with customizable width and height.           |
| [`revealjs`](qembedio-embed-revealjs.qmd) | Embeds a Reveal.js slide deck with optional height.             |

You can use the shortcode immediately in a Quarto project that has the extension installed by typing into the document:

```md
{{< shortcode-name filename >}}
```

For example, we can embed RevealJS slides using:

```md
{{< revealjs "assets/my-slides.html" >}}
```
